charts/istio-endpoints/Chart.yaml, charts/istio-endpoints/README.md, charts/istio-endpoints/templates/elasticache.yaml
Ooops:
```
error validating data: ValidationError(ServiceEntry.spec.endpoints[0]): unknown field "port" in io.istio.networking.v1beta1.ServiceEntry.spec.endpoints
```
=> [istio-endpoints] Bugfix on the ServiceEntry config

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml
```diff
$ VALUES=values.local.yaml make template > new && diff -b -u orig new
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/diranged/git/nextdoor/k8s-charts/charts/simple-app
--- orig	2021-06-10 06:50:39.000000000 -0700
+++ new	2021-06-10 06:55:41.000000000 -0700
@@ -98,9 +98,9 @@
imagePullPolicy: IfNotPresent
envFrom:
- configMapRef:
-                name: '{{ .Release.Name }}-test'
+                name: simple-app-test
- secretRef:
-                name: '{{ .Release.Name }}-sec'
+                name: simple-app-sec
resources:
{}
ports:
```
=> [simple-app] Run the envFrom settings through the tpl function

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml
To be able to arbitrarily customize the PodSpec labels
=> [simple-app] Add in a podLabels configuration parameter

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/values.yaml
update kubernetes namespace to be dynamic
=> Update kubernetes namespace to be dynamic

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/prometheusrule.yaml, charts/flink-job/values.yaml
* Add `FlinkCheckpointFailing` alert 
* Set alert severity as a part of the values
=> [flink-job] Update Prometheus alerts 

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/_helpers.tpl, charts/flink-job/templates/serviceaccount.yaml, charts/flink-job/values.yaml
pass in service account name from values
=> [flink-job] Pass in service account name from values 

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/prometheusrule.yaml, charts/flink-job/values.yaml
add job restarts limit to values
=> [flink-job] add job restarts limit to values

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml, charts/flink-job/values.yaml
Adding this field for Spotify flink operator we recently switched over to in https://github.com/Nextdoor/k8s/pull/508
=> [flink-job] Expose flinkVersion field

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml, charts/flink-job/values.yaml
To be compatible with the change on flink operator https://github.com/Nextdoor/k8s/pull/565.
=> [flink-job] Update yaml to be compatible with updated flink operator

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml, charts/istio-alerts/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
Adding HighLatency Alarms to the services.
=> Adding HighLatency Alarms to the services.

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/vpa.yaml
I put the setting into the Values file, but never used it in the template. 🤦
=> [daemonset-app] Add missing controlledValues setting to VerticalPodAutoscaler

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_datadog.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
```
ad.datadoghq.com/daemonset-app.logs: |-
[
{
"source": "daemonset-app",
"service": "daemonset-app",
"log_processing_rules": []
}
]
```
=> [nd-common]: Convert datadog logging values into json format

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/README.md.gotmpl, charts/nd-common/templates/_networkpolicy.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/networkpolicy.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/networkpolicy.yaml, charts/stateful-app/values.yaml
The goal of this PR is to simplify the process of creating a `NetworkPolicy` resource that grants internal cluster communication access to the services inside these applications.
=> [stateful/simple/nd-comon] Add in NetworkPolicy resource

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml
=> [simple/stateful/daemonset]: Add conditional support for startup probe

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_common.tpl, charts/nd-common/templates/_topology_spread_constraints.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/poddisruptionbudget.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/poddisruptionbudget.yaml
MatchExpressions is newer and more flexible. Also it is more well
supported by partners like Spot.io in their Ocean product.
=> [nd-common/simple-app/stateful-app] Use matchExpressions in TopologySpreadConstraints

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml
When nested charts merge the Values, the 'null' values don't translate
causing them to be wiped out of the final chart.
=> [simple-app] Use 'false' rather than 'null' (#155)

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_datadog.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
This is to help correlate UDP statsd traffic:
https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#origin-detection-over-udp
=> [nd-common] Set DD_ENTITY_ID

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
This includes an important fix to the rate() setting causing some of our alarms to potentially not fire off.
=> [simple/stateful/rollout] Update to istio-alerts chart 0.1.4

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/values.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/templates/rollout.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.yaml
Similar to #173 but also allows for extra sidecars and use of template variables.
=> [rollout/simple/stateful/daemon] Add optional sidecar and init containers

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml
[charts/flink-job] Allow specifying nodeSelector for job manager
=> [charts/flink-job] Allow specifying nodeSelector for job manager

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/values.yaml
[charts/flink-job] Increased metrics scraping interval for the flink-job
=> [charts/flink-job] Increased metrics scraping interval for the flink-job

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml
[charts/flink-job] Fixing line break that breaks deployment
=> [charts/flink-job] Fixing line break that breaks deployment

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml, charts/flink-job/values.yaml, ct.yaml
Add support for affinity to flink-jobs-chart. Also fix chart-testing.yaml to not validate maintainers
=> Add support for affinity to flink-jobs chart

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml
app-group specific values file should be last in the list so that it can override the previous values.
=> feat(charts/simple-workflow): Add additionalValueFiles before app-group specific values file

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/hpa.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/values.yaml
https://istio.io/latest/docs/reference/config/analysis/ist0118/
=> fix(charts): Rename metrics port to http-metrics (IST0118)

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml, charts/simple-workflow/values.yaml
Allow individual workflow to customize its own `ttlStrategy`
=> feat(charts/simple-workflow): Allow simple-workflow to specify ttlStrategy

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml
Sorry. I wish we have caught this with linting.
=> feat(charts/simple-workflow): Fix bad YAML introduced with adding verify job health tasks

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/values.yaml
Remove default probes to fix an issue of multiple probes.
=> fix(charts/daemonset-app): Remove default probes

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md
`nd-common` Changelog: https://github.com/Nextdoor/k8s-charts/compare/nd-common-0.2.0...nd-common-0.3.1#diff-a7159ef9b8026dc09b78a4807eada34df1343eed52d0cca991659978777d0199
=> fix(prometheus-alerts): Update nd-common subchart to proper version

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/runbook.md
Adding more description on the steps to take for KubeJobFailed
=> Adding to prometheus alerts runbook about KubeJobFailed

charts/flink-operator/Chart.yaml, charts/flink-operator/README.md, charts/flink-operator/templates/deployment.yaml, charts/flink-operator/values.yaml
The Operator image is AMD64 only.
=> feat(charts/flink-operator): run on amd64 nodes

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/runbook.md
Due to encoding issues, the direct link to graph is not in the alerts...
So adding the query here for easier lookup
=> chore(charts/istio-alerts): update runbook for 5xx increase

charts/simple-app/Chart.yaml, charts/simple-app/README.md
To pull in this fix: https://github.com/Nextdoor/k8s-charts/pull/332
=> fix(simple-app): update nd-common for single pod istio proxy sidecar injection

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/hpa.yaml
rollout-app HPA's targetscaleref should be pointing to a Rollout resource
=> update rollouts hpa scaletargetref

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl
Release notes for https://github.com/Nextdoor/k8s-charts/pull/338
=> chore(README): update upgrade notes for v1.2.x. to v1.3.x et al

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml
Fixes  "/dev/shm/2942512099": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.labels of type string
=> fix(charts/simple-app): use printf instead of explicit string for transition
