Nextdoor/k8s-charts

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml
**What I wanted?**
While passing in a list of standard-kubernetes-formatted `env` objects is what
we want the template to look like, I wanted the ability to use helm template
parsing in the Names and Values. This way you can dynamically refer to Secrets
and ConfigMaps from the main values.yaml.
**What does this do?**
Running the Env Name/Value pairs through the `tpl` function allows us to handle
this pretty gracefully without changing the interface at all.
**Example**
If I set up my `values.yaml` like this:
```yaml
env:
- name: VAR-{{ .Release.Name }}
value: MyValue-{{ .Release.Name }}
- name: VARFROM
valueFrom:
secretKeyRef:
name: '{{ .Release.Name }}-secret'
key: mykey
```
The final diff in the Deployment is:
```diff
install.go:173: [debug] Original chart version: ""
install.go:190: …
```
=> [simple-app] Run the env variables through the tpl parser

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml
This fixes a bug introduced in 0.2.0 where the `tpl` function could interpret a
stringified int as a number and return it as a number rather than its original
from of a string. All environment `value` keys must be a string, so force that
with the quote function.
=> [simple-app] Make sure to always quote the values in the env key

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/tests/test-connection.yaml, charts/simple-app/values.yaml, ct.yaml
The existing test-case was hard coded to a plain-text HTTP get with `wget` as the client. That doesn't make it easy to support alternative use-cases (gRPC for example).
Reconfigured the test suite so that all of the details are in the `values.yaml` file under the `tests.connection` key. This not only makes the test more configurable, but it also lets us start adding in other tests down the road that might be different and gives us independent control to configure them.
=> [simple-app] Make the chart "connection" test configurable

charts/simple-app/Chart.yaml, charts/simple-app/Makefile, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/ingress/ingress.yaml, charts/simple-app/templates/istio/networkpolicy.yaml, charts/simple-app/templates/istio/virtualservice.yaml, charts/simple-app/templates/tests/test-connection.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml
The existing `Ingress` and `VirtualService` handling was confusing and inconsistent. I wanted to
simplify it - by making an opinionated decision about the "Standard" resource configuration that
we should use.
1. Refactored the `Ingress` template so that the HTTP rules were hard-coded rather than using
big nested strings that are then run through `tpl`. The new opinionated framework more closely
matches what we do in our normal ALBs. This also just makes the template _much_ easier to
understand and document. If a user needs a custom Ingress, they can create it on their own.
2. Refactored the `VirtualService` template to also be highly opinionated and favor a very simple
single-service routing model. Custom `VirtualService` resources can be defined by …
=> [simple-app] Completely refactor the ingress/virtualService handling

charts/istio-endpoints/Chart.yaml, charts/istio-endpoints/README.md, charts/istio-endpoints/templates/sidecar.yaml
```
admission webhook "validation.istio.io" denied the request: configuration is invalid: host must be of form namespace/dnsName
```
The namespace needs to be included (or `.`).
=> [istio-endpoints] Bugfix on the Sidecar object

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/tests/test-connection.yaml, charts/simple-app/values.local.yaml
When you pass in a `sha256:...` image hash to a Pod spec, you need to use a `@` rather than a `:` separator.
=> [simple-app] Properly support when the image.tag is set to a sha256:value

.github/workflows/ci.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/servicemonitor.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml
This PR adds support for configuring metrics-collection in two ways - through a Prometheus `ServiceMonitor` resource, or through the Istio Sidecar using ["Metrics Merging"](https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging).
```diff
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/diranged/git/nextdoor/k8s-charts/charts/simple-app
--- orig	2021-06-21 16:40:29.000000000 -0700
+++ new	2021-06-22 07:00:39.000000000 -0700
@@ -8,7 +8,7 @@
metadata:
name: simple-app-ingress-access
labels:
-    helm.sh/chart: simple-app-0.9.5
+    helm.sh/chart: simple-app-0.10.0
app.kubernetes.io/version: "latest"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: simple-app
@@ -32,7 +32,7 @@
metadata:
name: simple-app
labels: …
```
=> [simple-app] Add support for Prometheus ServiceMonitors and Istio Metrics Merging

.github/workflows/ci.yaml, charts/local-kafka/Chart.yaml, charts/local-kafka/README.md, charts/local-kafka/templates/kafka.yaml, charts/local-kafka/values.yaml
I wanted to be able to access `local-kafka` from services running directly on my local machine, and was able to get something working by adding an external listener (https://strimzi.io/blog/2019/04/23/accessing-kafka-part-2) that advertises `127.0.0.1:32000` for the single broker, and then exposing that address in the kind config. 
Output from `make template`:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
name: default
spec:
kafka:
replicas: 1
livenessProbe:
initialDelaySeconds: 60
failureThreshold: 30  # 30 * 10s
readinessProbe:
initialDelaySeconds: 60
failureThreshold: 30  # 30 * 10s
authorization:
type: simple
superUsers:
- ANONYMOUS
jvmOptions:
'-Xmx': '384M'
'-Xms': '128M'
listeners:
- name: tls
port: 9092
type: internal
tls: true
authentication:
type: tls
- name: …
```
=> [local-kafka] Add external listener

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md
https://github.com/Nextdoor/k8s-charts/runs/3353281960 is detecting [changes to the runbook](https://github.com/Nextdoor/k8s-charts/commit/87f51e566fba62abc62d584ad597b7802f82fdad), and tries to re-release the chart, but `prometheus-alerts-0.1.4` already exists. 
I wonder if the `local-kafka` chart version needs to be incremented also, since https://github.com/Nextdoor/k8s-charts/releases/tag/local-kafka-0.1.0 got created?
=> [prometheus-alerts] Bump chart version to unblock release

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/test.yaml, charts/prometheus-alerts/values.yaml
I discovered a few things..
1. The `error` reason can include a pod being evicted gracefully.
2. The templating was broken in our alert text
3. The `OOMKilled` alert should definitely be separate so that you can have different thresholds
=> [prometheus-alerts] Split out the ContainerTerminated alert from an OOMKilled alert

charts/local-kafka/Chart.yaml, charts/local-kafka/README.md
The original change failed to be released (https://github.com/Nextdoor/k8s-charts/runs/3353281960), so I think we need to bump the version for the chart releaser to pick it up again.
=> [local-kafka] Bump chart version to trigger release

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml
Before a pod gets terminated, Kubernetes sends a SIGTERM signal to every
container and waits for period of time (30s by default) for all
containers to exit gracefully. If your app doesn't handle the SIGTERM
signal or if it doesn't exit within the grace period, Kubernetes will
kill the container and any inflight requests that your app is processing
will fail.
https://docs.flagger.app/tutorials/zero-downtime-deployments#graceful-shutdown
=> [simple-app] Add a default preStop lifecycle hook

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl
**What did I want**
I want Kiali to stop complaining that our services don't have a version label, when they already had the `app.kubernetes.io/version` label. I am adding in the `app/version` labels as well.
=> [simple-app] Add the app/version labels by default to all the resources

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/ingress/networkpolicy.yaml, charts/simple-app/templates/istio/networkpolicy.yaml, charts/simple-app/templates/service.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml
First, I want to make it easier and automatic for our applications to delay the shutdown of the `istio-proxy` sidecar app until after our web serving services have shut down. Second, I noticed that we do not handle the situation where no listener ports (`.Values.ports`) are supplied very well - this is a reasonable thing to handle as it is how any non-web-service is likely to operate.
* _Fixed `.Values.ports` handling_: If the `.Values.ports` is supplied as an empty list, or a `nil` value, then we no longer try to create NetworkPolicies.
* _Automatic preStop command_: If Istio is enabled, and the `.Values.ports` list is greater than 0, then we default to using the automatic prestop command that scans for listening ports before shutting down.
* …
=> [simple-app] Bake in the istio preStop command, and fix our empty port handling

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/istio/virtualservice.yaml, charts/simple-app/values.yaml
It's reasonable that some services would want to explicitly allow-list paths, rather than just passing in an entire path prefix. This allows requests to be blocked at the IngressGateway level before it ever gets to the `istio-proxy` sidecar container.
While trying to keep this simple, I wanted to allow multiple paths to be set... at a certain point, it makes more sense for a developer to just manage their own `VirtualService` object. I think though that this is a reasonable and common option.
**Diff**
Given the following config change to `values.local.yaml`:
```diff
diff --git a/charts/simple-app/values.local.yaml b/charts/simple-app/values.local.yaml
index 41f229e..e592e84 100644
--- a/charts/simple-app/values.local.yaml
+++ …
```
=> [simple-app] Allow VirtualService resources to explicitly allow-list certain paths

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/istio/virtualservice.yaml, charts/simple-app/values.yaml
Example diff:
```diff
$ make template > new && diff -b -u orig new
...
--- orig	2021-09-21 14:44:12.000000000 -0700
+++ new	2021-09-21 14:44:15.000000000 -0700
@@ -514,6 +514,16 @@
- match:
- uri:
prefix: /
+      corsPolicy:
+        allowCredentials: false
+        allowHeaders:
+        - X-Foo-Bar
+        allowMethods:
+        - POST
+        - GET
+        allowOrigins:
+        - exact: https://example.com
+        maxAge: 24h
route:
- destination:
host: simple-app
```
=> [simple-app] Add in a parameter for the corsPolicy

charts/flink-job/Chart.yaml, charts/flink-job/README.md
No clear reason why, but the chart-releaser tool failed to release the 0.1.0 release.
=> [flink-job] Rebuild with new version

.github/workflows/ci.yaml
This reverts commit 458ed5485b2910b6898a649b611d9092aaab5aec.
@sabw8217 For some reason this causes the CRD install to break. The build failure at https://github.com/Nextdoor/k8s-charts/runs/3839257790?check_suite_focus=true looks like this:
```
The CustomResourceDefinition "flinkclusters.flinkoperator.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
```
For now I am reverting this. We can try to troubleshoot this and submit a PR upstream to the Spotify team.
=> Revert "Use a recent version of the spotify CRD. (#72)"

charts/local-kafka/Chart.yaml, charts/local-kafka/README.md
This newer operator is built so it can operate on an ARM64 M1 mac in
emulation mode, while the older operator does not.
=> [local-kafka] Upgrade the Strimzi Operator to 0.25.0

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml, charts/flink-job/values.yaml
Flink operator uses mutating webhook to set default values for some fields in CRDs, https://github.com/spotify/flink-on-k8s-operator/blob/5f2c73a16f9040cb06cd9665e6a59b77d2280709/api/v1beta1/flinkcluster_default.go. As we try to scope down the operator to namespace level with webhook disabled, we need to expose these fields with default values set.
=> [flink-job] Expose job mode and JM replicas

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/_helpers.tpl, charts/daemonset-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/_helpers.tpl, charts/stateful-app/values.yaml
When using ArgoCD and the ArgoCD Image Updater, we want to allow the
image updater to do its job (setting `.image.tag`), but also allow for
humans to override the updater. Creating a new `image.forceTag` setting
lets a human with access to the `Application`. The argocd-image-updater
will not have any idea that it's change is being overridden, and this
new setting makes it more clear to application owners that a
human-introduced change has been applied.
=> [simple/daemon/stateful-apps] Support overriding the image Tag manually

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml
Got this error after enabling `datadog.scrapeMetrics`:
```
error validating data: ValidationError(Deployment.spec.template.metadata.annotations.ad.datadoghq.com/istio-proxy.check_names): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "array", expected "string"
```
https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes
=>  [simple/daemon/stateful-apps] Use string for Datadog check_names annotation

charts/istio-endpoints/Chart.yaml, charts/istio-endpoints/README.md, charts/istio-endpoints/templates/sidecar.yaml, charts/istio-endpoints/values.yaml
I have a job that makes requests to pods in another namespace in the mesh. I want to run it as a `PreSync` hook, but that means that the custom sidecar configuration won't be applied yet at that point. I also want the sidecar to be created before the job is run, and was thinking of using [waves](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/) to do that?
=> [istio-endpoints] Allow custom annotations on sidecar

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.yaml
We were missing the `"metrics"` key - which meant that if you tried to have Datadog scrape your metrics endpoints nicely through our chart config, it would fail with this error: 
```
datadog_checks.base.errors.CheckException: You have to collect at least one metric from the endpoint: http://100.64.42.155:15020/stats/prometheus
```
=> [statefulset/simpleapp/daemonset] Set the proper datadog "metrics" scrape config

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml
The motivation of introducing another field into .Chart.Name here is to
make it easier to identify where the "ServiceRules" are coming from -
without this, they appear to be natively part of the parent-chart
(simple-app for example). With the .Chart.Name in there, you can more
easily see that these come from a nested chart.
=> [istio-alerts] Introduce .Chart.Name into Rule Names

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml
**Update: Helm Bug**
I've discovered a bug that took me the better part of all of yesterday to figure out. I couldn't understand why I was unable to disable the `istio-alerts` chart [(alias'ed to `istioRules` in simple-app)](https://github.com/Nextdoor/k8s-charts/pull/97/files#diff-01d4bc68d5049882db28ae0896ab77392652b798a14592fdd04f330c321984c5R13). Every time I ran the template, the `app1` chart would properly bypass creating the service-rules template... but the `app2` chart would create it. Weirder yet, the name of the `app2` chart's template clearly indicated it was using the `istio-alerts` name instead of the `istioRules` alias. I thought I was losing my mind... or having a caching bug.
**The bug**
To test this, I learned a little trick... create a `templates/test.yaml` file with …
=> [simple-app] Bugfix, undo alias'ing of the dependency chart

charts/prometheus-alerts/runbook.md
Unfortunately this is a very general alert, so the runbook can only provide high level direction.
=> Add a runbook for `KubePodNotReady`

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/_helpers.tpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/service.yaml, charts/simple-app/templates/servicemonitor.yaml, charts/simple-app/values.yaml
I am working on using this chart to implement [YACE](https://github.com/nerdswords/yet-another-cloudwatch-exporter) - which is a service collects metrics from CloudWatch and exports so a ServiceMonitor can scrape them into Prometheus. I discovered a few bugs though with the way our `Service`, `ServiceMonitor` and `Deployment` resources were handling port configuration.
=> [simple-app] Fix the ServiceMonitor and improve the Ports configuration

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/hpa.yaml
https://github.com/kubernetes/kubernetes/issues/74099
=> [simple-app] Re-order HPA metrics

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml
The intent here is to fix this [build error](https://github.com/Nextdoor/hello-world-k8s.template/pull/11/checks?check_run_id=5069569863) by defaulting to a curl version that should support `--retry-connrefused`.
=> simple-app: Prefer latest curl image by default

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/vpa.yaml, charts/daemonset-app/values.yaml
This PR adds in management of a `VerticalPodAutoscaler` resource for the `daemonset-app` chart. I intend to add this to some of the other charts down the road, but the `daemonset-app` chart makes the most sense right now because we have a few daemonsets where the resources are very much situationally dependent ... and trying to tune the resource requests by hand is unreasonable.
=> [daemonset-app] Add in a verticalAutoscaling configuration

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/_helpers.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/_helpers.tpl
The latest version of the ArgoCD Image Updater uses a newer syntax when setting the SHA hash for a docker image - instead of it being `image: foobar@sha256:.....` its `image: foobar:latest@sha256:...`. This means that our parsing of the `$tag` value needs to change.
=> [simple/stateful/daemon] Replace any "@" in the $tag for labels

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml
1. We were not setting the namespace label, which meant the alerts were
going into the ether.
2. We were not using avg() but instead sum() - which meant that we were
ADDING all the cumulative latency numbers!
=> [istio-alerts] Bugfixes on the HighRequestLatency alarm

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/Makefile, charts/nd-common/templates/_node_selector.tpl, charts/nd-common/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.yaml, ct.yaml
This PR introduces a whole new "Library" chart**. The new "nd-common"
library chart will be a single place where we keep all of our common
goodies and helpers. These helpers can then be leveraged by our various
common (or app-specific) charts to provide common behaviors across the
board, without requiring complex dependency chart management.
The simple-app, statefull-app and daemonset-app charts have all been
updated to use the new "nd-common.nodeSelectors" definition, which adds
in default behaviors for setting the "kubernetes.io/os" and
"kubernetes.io/arch" nodeSelectors on our pods.
**: https://helm.sh/docs/topics/library_charts/
=> [nd-common] Implement a new nd-common library chart

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/README.md.gotmpl, charts/nd-common/templates/_istio.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/values.yaml
By explicitly enabling or disabling it, we don't have any accidental situations where someone will get metrics scraped by Envoy and a separate PodMonitor all at the same time. We maintain the ability to turn this feature on, but default it to Off.
=> [simple/daemon/stateful-app] Explicitly enable or disable metrics merging

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_monitors.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/values.yaml
We were missing some default labels that we apply to all of our metrics.
All the `app.kubernetes.io/` and `tags.datadoghq.com` labels. Adding
these back in should fix some dashboards.
=> [nd-common] Update the PodMonitor relabelings configuration

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/values.local.yaml, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/README.md.gotmpl, charts/nd-common/templates/_common.tpl, charts/nd-common/templates/_datadog.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/ci/datadog-with-env-values.yaml, charts/simple-app/ci/datadog-without-env-values.yaml, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.local.yaml, charts/stateful-app/values.yaml
This PR adds support for providing custom container name to simple-app/daemonset/stateful-app. If not specified, it will default to `.Chart.Name` . Also it adds functionality to scrape application logs by Datadog. It adds support for providing tags (service and source) along with advanced log processing rules configuration https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=docker .
Proof it works
=> [nd-common/simple/daemon/stateful-app]: Support for custom container name and Datadog logging configuration

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.yaml
**Why?** 
Protect slow starting containers with startup probes
Some applications might require an additional startup time on their first initialization. In such cases, it can be tricky to set up liveness probe parameters without compromising the fast response to deadlocks that motivated such a probe. The trick is to set up a startup probe with the same command, HTTP or TCP check, with a failureThreshold * periodSeconds long enough to cover the worse case startup time.
The kubelet uses startup probes to know when a container application has started. If such a probe is configured, it disables liveness and readiness checks until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding …
=> [simple-app/stateful/daemonset]: Add support for Startup Probes

charts/local-kafka/Chart.yaml, charts/local-kafka/README.md, charts/local-kafka/values.yaml
`strimzi-kafka-operator` 0.26.0 takes forever to start on M1 chip, and it seems that version doesn't have a tag for arm64 neither. 0.28.0 takes 4-5mins on my M1, which is still be slower than Intel, but is significantly faster than previous version. Also exposed image config in values.yaml for customized settings.
=> [local-kafka] Update strimzi kafka operator to 0.28.0

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl
The value for `proxySidecar.image.tag` was being ignored in `simple-app.proxyImageFqdn` leading to the main image tag always being used
=> Fix simple-app ignoring the sidecar image tag

.github/workflows/ci.yaml, Makefile, charts/rollout-app/.helmignore, charts/rollout-app/Chart.yaml, charts/rollout-app/Makefile, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/ci/bluegreen-values.yaml, charts/rollout-app/ci/canary-values.yaml, charts/rollout-app/ci/local-values.yaml, charts/rollout-app/templates/NOTES.txt, charts/rollout-app/templates/_helpers.tpl, charts/rollout-app/templates/hpa.yaml, charts/rollout-app/templates/ingress/ingress.yaml, charts/rollout-app/templates/ingress/networkpolicy.yaml, charts/rollout-app/templates/istio/networkpolicy.yaml, charts/rollout-app/templates/istio/virtualservice.yaml, charts/rollout-app/templates/kmssecret.yaml, charts/rollout-app/templates/networkpolicy.yaml, charts/rollout-app/templates/poddisruptionbudget.yaml, charts/rollout-app/templates/podmonitor.yaml, charts/rollout-app/templates/prometheusrules.yaml, charts/rollout-app/templates/rollout.yaml, charts/rollout-app/templates/secret.yaml, charts/rollout-app/templates/serviceaccount.yaml, charts/rollout-app/templates/services.yaml, charts/rollout-app/templates/tests/test-connection.yaml, charts/rollout-app/values.local.yaml, charts/rollout-app/values.yaml
As we begin using [Argo Rollouts](https://argoproj.github.io/argo-rollouts/) - we need a new default application template that can create the `Rollout` objects, as well as the more customized `VirtualService` and `Service` resources. I wanted to enable us to begin experimenting with these deployment models in a simple way.
A newly created `rollout-app` chart has been created along with some customization to the Github Workflow. The workflow now detects if the `rollout-app` chart was updated, and if it was, we then install the Argo Rollouts controller/CRD for the tests. When the tests run, we verify that we can create both a `BlueGreen` and `Canary` rollout resource type. We are explicitly not testing actually triggering a rollout - we don't need to …
=> [rollout-app] New Argo Rollouts based Deployment

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/README.md.gotmpl, charts/nd-common/templates/_topology_spread_constraints.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml, charts/stateful-app/values.local.yaml, charts/stateful-app/values.yaml
The original setup allowed you to pass in a `TopologySpreadConstraints`
list of maps ... but we did no template parsing, no validation, and we
provided no intelligent way to set the `labelSelector` key.
This PR does two things. First we intelligently parse the
`TopologySpreadConstraints` maps that the user supplies, error out
appropriately, and then insert the `labelSelector` automatically.
Second, we create a default topology spread constraint that spreads
across AZs, allowing users to just flip a boolean flag and get the
spread done in the simplest possible way.
=> [stateful/simple/nd-common] Implement a smarter TopologySpreadConstraint configuration

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_annotations.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml
Per an outside discussion, this adds a common definition of labels that we use on the majority of Pods we create, and (initially) demonstrates its use on simple-app. Other charts will follow once the approach is settled.
=> Add nd-common.podAnnotations helper and demonstrate it with simple-app

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/_helpers.tpl, charts/simple-app/templates/istio/virtualservice.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/istio/virtualservice.yaml
If there are no `.Values.ports` exposed, then we do not create a `Service` for the application. In that case, we should also not create a `VirtualService` because it would not have anything to point to and it represents an "error" in Istio.
=> [simple-app/stateful-app] Avoid creating the VirtualService if there are no ports

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_common.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/README.md.gotmpl, charts/prometheus-alerts/templates/_helpers.tpl, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
The prometheus-alerts chart was too widely scoped. This would make it
difficult to run multiple Applications within a single Namespace that
each define their own prometheus-alerts charts.
This change significantly breaks backwards compatibility - hence the
major version upgrade. The new code narrowly scopes the alerts by
default, and provides overrides to let a developer widen their scope.
=> [prometheus-alerts/nd-common] Scope down the prometheus-alerts

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/values.yaml
I forgot that the various resource names are going to be `{{ .Release.Name}-{{ .Chart.Name }}`
in most cases, which means that we need to use the `-.*` wildcard selector.
=> [prometheus-alerts] Use the wildcard selector by default

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml
When nested charts merge the Values, the 'null' values don't translate
causing them to be wiped out of the final chart.
=> [daemonset-app] Use 'false' rather than 'null'

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/prometheusrules.yaml, charts/daemonset-app/values.yaml, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/README.md.gotmpl, charts/prometheus-alerts/templates/_helpers.tpl, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/templates/pagerduty-alertmanagerconfig.yaml, charts/prometheus-alerts/templates/pagerduty-routing-key-externalsecret.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/prometheusrules.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/prometheusrules.yaml, charts/stateful-app/values.yaml
Unfortunately the use of nested-nested helm charts (ie, `myapp -> simple-app -> prometheus-alerts`) is fine when you only do it once. .. but when you run multiple versions of those nested sub charts, Helm squashes them into a common namespace and it causes all kinds of conflicts. This was the original reason I pulled the `prometheusRules` into the `simple-app` chart to begin with.
I finished the job of migrating all the custom prometheusRules into each of the daemons/stateful/simple-app charts. There is some duplication of effort here, but not a lot.
=> [simple/daemon/stateful] Revert to using in-template prometheusrules

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_service.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/values.yaml
This was previously present in the daemonset-app, but I accidentally
removed it. This is a useful override, adding it back everywhere.
=> [stateful/daemonset/rollout/simple] Add in Values.service.name override

.gitignore, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/ingress/ingress.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/ingress/ingress.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/ingress/ingress.yaml
I have no idea if this applies to our environment but I found this annotation we can add if we do use this controller. https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#resource-tags
This is the only real change: https://github.com/Nextdoor/k8s-charts/pull/163/files#diff-d8238429e8bf4db0c7df1c76b65983a05a6ced2407910a6f5aac1e4be3fe2eafR24
=> [simple-app/rollout-app/stateful-app] Add AWS tags to ingress LB

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/prometheusrules.yaml, charts/daemonset-app/values.yaml, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/prometheusrules.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/prometheusrules.yaml, charts/simple-app/templates/tests/test-connection.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/prometheusrules.yaml, charts/stateful-app/values.yaml
The rules we had in place to catch Pods in a CrashLoopBackoff state were
too complicated and easily missed pods depending on the situation. A
much cleaner metric exists with a very clear selector for
`CrashLoopBackOff`, so I am rewriting the rules to use that.
https://www.circonus.com/2021/01/guide-to-monitoring-kubernetes-part-2-which-metrics-and-health-conditions-you-should-be-monitoring/
=> [all charts] Fix some bad ContainerWaiting/CrashLoop Rules

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/poddisruptionbudget.yaml
We have seen few times that replica count for deployment and pdb is configured as 1. It causes issue while scaling and draining the node. In order to configure PDB, deployment replica count should be set to minimum of 2. This PR adds that check. If replica count is less than 2, then helm will throw error. 
Proof it works
```
saansh45 ~/Code/k8s-charts/charts/simple-app (pdb_replica_count_check) $ make template
Pulling dependencies in...
helm dependency update .
walk.go:74: found symbolic link in path: /Users/angadpatil/Code/k8s-charts/charts/simple-app/ci/local-values.yaml resolves to /Users/angadpatil/Code/k8s-charts/charts/simple-app/values.local.yaml
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://k8s-charts.nextdoor.com" chart …
```
=> [simple-app]: Add minimum replica count check for PDB configuration

charts/istio-endpoints/Chart.yaml, charts/istio-endpoints/README.md, charts/istio-endpoints/templates/elasticache.yaml
Ensure Envoy uses the Redis cluster aware loadbalancer so that it understand the cluster topology and can route requests to a node responsible for the target key's hash slot.
=> set cluster lb policy so envoy understands the redis cluster topology

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml
When most of our pod metrics are collected every minute now, we can't run a rate() function over a 1m timestamp beacuse there aren't 2 datapoints. Changing this to 5m.
=> [all charts] Replace 1m rate functions with 5m

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_istio.tpl
Tested locally with various combinations of `istio.enabled`, `monitor.enabled`, and templated and non-templated values for the ports.
Ex:
```
istio:
enabled: true
excludeInboundPorts:
- '{{ .Values.database.port }}'
- 1234
monitor:
enabled: true
portNumber: 9090
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: gnarfeed-read
labels:
helm.sh/chart: read-0.4.2
app.kubernetes.io/version: "local"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: read
app.kubernetes.io/instance: gnarfeed
spec:
replicas: 1
revisionHistoryLimit: 3
selector:
matchLabels:
app.kubernetes.io/name: read
app.kubernetes.io/instance: gnarfeed
template:
metadata:proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
traffic.sidecar.istio.io/excludeInboundPorts: "5432, 1234, 9090"
```
=> [nd-common] Support templated values in excluded Istio inbound ports

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_monitors.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/values.yaml
These filters can be overridden - but by setting some default ones, we can avoid bringing a bunch of high cardinality and noisy metrics that are mostly not being used.
=> [nd-common] Remove pod_name label, implement default filter for go/process metrics

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml
We assume that if somebody is explicitly setting the replica count to `null` and enabling PDBs, they know what they're doing and probably have custom autoscaling or something.
=> [simple-app] Allow PDB creation if replica count is null

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml
We bucket in units of 1m, therefore this time must be greater. I greped for s] and 1m so I think this was the only case less than or equal to a minute in the repo
=> just fix rollup time

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml
Setting default `readinessProbe`s and `livenessProbe` is potentially helpful for web services but more and more we're building services that do not follow this pattern. Furthermore, we should encourage application writers to think concretely about what to set these probes since we've run into issues in the past with them being the same where they really should have been different.
Major version bump as this is a breaking change.
=> BREAKING CHANGE: remove default readiness and liveness probes

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/ci/datadog-with-env-values.yaml, charts/simple-app/ci/datadog-without-env-values.yaml, charts/simple-app/ci/proxy-values.yaml, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml
The `livenessProbe` and `readinessProbe` changes made in
https://github.com/Nextdoor/k8s-charts/pull/212 were invalid. In the `1.1.2`
release I fix these checks. Going forward `livenessProbe` is optional, but
`readinessProbe` is a required field.
=> fix(charts/simple-app): fix the liveness/readinessprobe checks

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml, charts/simple-workflow/values.yaml
What is this ?
- This PR adds on to the  existing simple-workflow that checks on argocd app health to also look for one or many `kind: job` 's health within the same argocd app.
Why do we need this ?
- Currently, simple-workflow requires a `kind: Job` to not be an [argo hook](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/).
- Having a job as hook is beneficial because we can decide if we want to run is Pre, Post or During sync.
- This change will enable argocd applications to have hooks that can run as part of their sync and ensure they are healthy too.
=> Adding support for batch job/s in simple-workflow

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml
- The batch Job has a different status than an application. 
- I updated the success condition to check for status.conditions[0].type == Complete
- Tested by running 
```
k wait --for=jsonpath='{.status.conditions[0].type}'=Complete  job.batch/schema-sync
job.batch/schema-sync condition met
```
=> fix(charts/simple-workflow): Update the successCondition of a job

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml, charts/istio-alerts/values.yaml
We switched to using federated metric collection so the `istio_requests_total` metric no longer exists. We need to be using `istio_requests:increase5m` to count the actual 5xx's.
Additionally, this chart needed some more flexibility to be able to be launched multiple times in a single namespace targeting different `destination_service_names` with different thresholds.
Finally, the alerts need to be split out across `reporter=source` and `reporter=destination` so that the application owners are alerted both if their own `istio-proxy` sidecar is reporting errors (thus definitely happening in their own app), and also if the `istio-ingressgateway` pods are reporting errors (which could be network problems, no healthy upstream issues, etc).
**Proof: `istio_requests:total5m`**
Here is an …
=> fix(charts/istio-alerts): use federated rolled up metrics

.github/workflows/ci.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_service.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/istio/virtualservice.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/istio/virtualservice.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/istio/virtualservice.yaml, ct.yaml
If the chart sets `.Values.service.name=xxx`, then we need to use that value in the `VirtualService` route - otherwise we create a route to a non-existent destination.
=> fix(all): use service.name in virtualservice route if supplied

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_service.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
Currently we create single service which includes service monitoring port. Istiod processes all these service ports. We use Prometheus Operator which uses ServiceMonitor and PodMonitor objects to determine endpoints to scrape.  So within service mesh, we don't care about service monitoring ports being exposed to envoy sidecar config. This PR simplifies the process of creating these services as 
In all of our k8s-charts repos we break out the Service objects into two objects. $serviceName and $serviceName-metrics.
The $serviceName Service only exposes the application ports, not the monitoring ports.
The $serviceName-metrics Service exposes only the Metrics port (and is only created if we are creating a ServiceMonitor).
The $serviceName-metrics service gets the networking.istio.io/exportTo: …
=> feat(all): refactor service creation for application and monitoring

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/templates/kmssecret.yaml, charts/daemonset-app/templates/secret.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/kmssecret.yaml, charts/rollout-app/templates/rollout.yaml, charts/rollout-app/templates/secret.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/kmssecret.yaml, charts/simple-app/templates/secret.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/kmssecret.yaml, charts/stateful-app/templates/secret.yaml, charts/stateful-app/templates/statefulset.yaml
When using multiple `simple-app` charts as a dependency in a single parent chart, it turns out that the `KMSSecret/Secret` resources were conflicting in name because they were not using our standard naming template function.
=> fix(charts): make sure to name the secrets uniquely

.github/workflows/ci.yaml, charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-janitor.yaml, charts/simple-workflow/templates/workflow-pipeline.yaml
This PR adds a component to `simple-workflow` which only keeps the last N recent workflow instances.
This solves the problem when an Argo Workflow is deployed as part of an Argo Application sync and the latest workflow instance is deleted due to `ttlStrategy` or `retentionPolicy`, the Argo Application is marked as Missing/OutOfSync, and the alert (e.g. PagerDuty) is triggered.
If `.Values.workflowJanitor.enabled` is not specified or `false`, the component is a no-op.
This PR also updates the Helm version to 3.12.2 to support `and` operator in the Helm template.
=> feat(charts/simple-workflow): Workflow Janitor

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/daemonset.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_common.tpl, charts/nd-common/templates/_datadog.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/rollout.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/statefulset.yaml
Per the docs at
https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes - we should not only be labeling our Pods, but the Deployments they're a part of. This PR takes that one step further and just adds the datadogLabels to all of our resource labels. The motivation here is that going forward anything that the Datadog team can use to correlate our resourcs will all be joined together with common labels.
=> feat(all charts): improve datadog tagging and correlation

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/workflow-pipeline.yaml
Once an Argo App is created, the current simple-workflow chart cannot update the helm, path and repoURL fields, this prevents us from migrating the Argo App's Helm chart to a different directory or a different repo.
This PR sets the helm, path and repoURL when updating the Argo App in simple-workflow.
=> feat(charts/simple-workflow): Update helm, path and repoURL when updating an Argo App in simple-workflow

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_istio.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
**Motivation**
Due to an incident, we found out that once one of the values is set through annotation. It overides the other values which is what led to the incident.
This behaviour is not documents nor it makes sense in any ways.
**Description**
Once a value is set to any of the istio.(proxyCPU, proxyCPULimit, proxyMemory, proxyMemoryLimit), all the 4 annotations will get created.
Fallbacking to the current implemented default resources for any annotation that is not specifically set:
Limits:
cpu:                2
memory:             1Gi
Requests:
cpu:                100m
memory:             128Mi
The PR includes:
- Adding support for istio sidecar resource override in nd-common istio-annotations.
- Updating dependant charts to use the new nd-common.
=> feat(charts/nd-common): Adding support for istio sidecar resource override

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/sealedsecret.yaml, charts/daemonset-app/values.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/templates/sealedsecret.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/sealedsecret.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/sealedsecret.yaml, charts/stateful-app/values.yaml
We have secretsEngine for:
-  `plaintext` (for regular k8s resource "Secret")
- `kms` (for resource "KMSSecret").
This adds secretsEngine support for `sealed` (for resource "SealedSecret" from [Bitnami Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets)).
```
secretsEngine: plaintext
secrets:
foo: bar
```
```
secretsEngine: sealed
secrets:
foo: AgATvuwJ73WsrfdjBgy3ack++p4D8PpPIKas4B9KD4wPzKhPTkJCYZSxsA6h12cqPNdWMc4wrzgldKluVZY/g8Kmn0u54kupAr04WV9FXVUekCLtKl210MEffbZCbrUDQ58Yegpy7wSBgy6/qBynqq0Bj0qPXbHZiVNgQimefyeeB36Vw8JdZ6JoIPto8AdpIZADa6buIGBsj0+cyLbrL1RP04s7jq+uAi8V1ro6vtdtv6RPHttNBFrOHQpjBhhSNu5X/dAIlMLGfvs0oV+udHG6lDhYQdaG5DJZCImXFnIU86qUSCS318GuGSXwoSejytsZimOw5U1oFu67RBHj6FzsmEc15mkAEKy51FsqSutQL6QnpWlBTvTcLYLi/qSKMTLC0+oqw6FC8e+d2k8zZL8nDffqgtwCa9GRwtby1R1OP0+7g1GawYlHA …
```
=> feat(simple-app): Add secretsEngine support for Sealed Secrets

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/kmssecret.yaml, charts/daemonset-app/templates/sealedsecret.yaml, charts/daemonset-app/templates/secret.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/kmssecret.yaml, charts/rollout-app/templates/sealedsecret.yaml, charts/rollout-app/templates/secret.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/kmssecret.yaml, charts/simple-app/templates/sealedsecret.yaml, charts/simple-app/templates/secret.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/kmssecret.yaml, charts/stateful-app/templates/sealedsecret.yaml, charts/stateful-app/templates/secret.yaml
After some private feedback (and I tend to agree), we want to _remove_ the `uppercase` transformation on secret property keys.
As the rest of the engines (`plaintext` and `kms`) are in abundant use, changing that would be BREAKING. 
I feel we can switch the `sealed` engine template only, as adoption of that is nil (and IMO a breaking change later for the rest of the secret engines).
I think the advantage of letting user explicitly set the key name (rather than doing a "behind-the-scenes" transformation) outweigh the cons (less friction finding/debugging secrets, some 3rd-party charts may require user to have a secret with a specifically styled key, etc)
=> chore(simple-app): remove uppercase transform of secret engine keys

charts/simple-workflow/Chart.yaml, charts/simple-workflow/README.md, charts/simple-workflow/templates/sealedsecret.yaml
Related to what was done for other charts as well: https://github.com/Nextdoor/k8s-charts/pull/261 (Ideally, `simple-workflows` would've been added to that as well).
```
secretsEngine: plaintext
secrets:
foo: bar
```
```
secretsEngine: sealed
secrets:
foo: AgATvuwJ73WsrfdjBgy3ack++p4D8PpPIKas4B9KD4wPzKhPTkJCYZSxsA6h12cqPNdWMc4wrzgldKluVZY/g8Kmn0u54kupAr04WV9FXVUekCLtKl210MEffbZCbrUDQ58Yegpy7wSBgy6/qBynqq0Bj0qPXbHZiVNgQimefyeeB36Vw8JdZ6JoIPto8AdpIZADa6buIGBsj0+cyLbrL1RP04s7jq+uAi8V1ro6vtdtv6RPHttNBFrOHQpjBhhSNu5X/dAIlMLGfvs0oV+udHG6lDhYQdaG5DJZCImXFnIU86qUSCS318GuGSXwoSejytsZimOw5U1oFu67RBHj6FzsmEc15mkAEKy51FsqSutQL6QnpWlBTvTcLYLi/qSKMTLC0+oqw6FC8e+d2k8zZL8nDffqgtwCa9GRwtby1R1OP0+7g1GawYlHAv+URLfjdJZmZF4vKzwxMBuHzXfJqj7aVSqLmpl29eDnjkhyEue0FAgYODoHneUxHvKQ7VqoFAt8n+t+2ZBcD+/ddslqgvUYG6lshQe …
```
=> feat(simple-workflow): Add secretsEngine support for Sealed Secrets

charts/flink-operator/Chart.yaml, charts/flink-operator/README.md, charts/flink-operator/templates/podmonitor.yaml
Changing pod monitor label from `cluster` to `flink-cluster` for flonk-operator, per [this](https://nextdoor.slack.com/archives/CM6EWSYH4/p1710968293931579) discussion.
=> [Flink operator] Rename pod monitor label from cluster to flink-cluster

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml
Right now the main "app" container and the "proxySidecar" container share the same probes.
As each container may be different, this can result in health check issues and we have no way of customizing a probe for each of the containers.
To maintain backwards compatibility, this will set the proxy sidecar's probes to whatever is set in `proxySidecar.*Probe` (and if it's not set, default to the current behavior of using the probe from the root.
=> feat(simple-app): Support optional different probes for proxySidecar

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/README.md.gotmpl, charts/istio-alerts/runbook.md, charts/istio-alerts/templates/service-prometheusrule.yaml, charts/istio-alerts/values.yaml
> [!WARNING]
> Reminder for @LaikaN57 - Update other charts in this repo after this PR is merged.
Split from https://github.com/Nextdoor/k8s-charts/pull/285
We ran into an issue where unbeknownst to us, our pod selector was set incorrectly and therefore all of our rules deployed via prometheus-alerts did not have any series to evaluate. This lack of series data is silently ignored. Here we are resolving this by implementing a rule which will use the various selectors to see if a basic metric exists or not. If it does not exist then we want to warn the user that non of the other rules will be evaluated.
Snippet from the other PR about using `kube_service_info` as our test metric.
> I think I see what you're doing here ...  but I see a risk. If there is no traffic to the service for …
=> feat(istio-alerts): Add service selector validity alert

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/_helpers.tpl, charts/istio-alerts/templates/service-prometheusrule.yaml
This PR follows patterns established in https://github.com/Nextdoor/k8s-charts/blob/8655ff4458e309e86232c4ae0a1fecfcb2cbf0c3/charts/prometheus-alerts/templates/_helpers.tpl#L21-L59
Proof:
```diff
akennedy@ndm2a istio-alerts % diff -bu orig new
--- orig        2024-04-17 16:29:11
+++ new 2024-04-17 16:27:28
@@ -59,17 +59,11 @@
expr: >
sum by (destination_service_name, reporter, source_workload) (
istio_requests:increase5m{
-            response_code=~"5.*",
-            destination_service_namespace="monolith",
-            destination_service_name=~".*"
-          }
+            response_code=~"5.*",destination_service_name=~".*", destination_service_namespace="monolith"}
)
/
sum by (destination_service_name, reporter, source_workload) (
-          istio_requests:increase5m{
- …
```
=> chore(istio-alerts): Add common selector helper for istio and ksm metrics

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/templates/service-prometheusrule.yaml, charts/istio-alerts/values.yaml
**Context**
In https://github.com/Nextdoor/k8s-charts/commit/c8308088b2acdf509ee3c3c5c431534710210fd8 there was a change to the way the service level 5XX alarm worked such that it computes an alarms on the 5XX rate individually for each source service. 
While it is valuable to have an alarm from the "client"'s perspective from reporting, and provide capabilities for there to be an alarm on arbitrary grouping keys, this wasn't the historical behavior, and the alarm has a different meaning. 
**Proposal**
To improve the behavior, I am first moving the definition of these labels into a value so that in a subsequent PR we can change the default behavior to match the intention before https://github.com/Nextdoor/k8s-charts/commit/c8308088b2acdf509ee3c3c5c431534710210fd8 
The intention o this …
=> feat(charts/istio-alerts): Part1: Parameterize the set of labels used for grouping 5XX alarms

charts/istio-alerts/Chart.yaml, charts/istio-alerts/README.md, charts/istio-alerts/README.md.gotmpl, charts/istio-alerts/values.yaml
As a follow up to https://github.com/Nextdoor/k8s-charts/pull/290 this change actually adjusts the alarm to remove the source workload from the grouping keys.
As a service owner, we want to provide out of the box visibility to the health of the service with appropriate false positives and false negatives. The current approach can create a high rate of false positives in the case of a very low volume source service intermingled with a higher volume source. This is currently happening with the content service which has 99.9% of traffic from the monolith and a small fraction of traffic via Bender, and was the impetus for the change. 
```diff
➜  istio-alerts git:(fix-service-alarm-10) ✗ make helm template >> new.yaml
install.go:218: [debug] Original chart version: ""
install.go:235: [debug] …
```
=> feat(charts/istio-alerts): Remove source service from 5XX Alarm

charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl
This propagate the istio-alerts update. It must be done as a separate PR and only merged after due to the use of http for referencing the charts repo
=> fix(charts/simple-app): Update istio-alerts

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/README.md.gotmpl, charts/prometheus-alerts/templates/_migrations.tpl, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.yaml
Values files schema has been updated to group alerts by resource type
Motivation: We have regrouped alerts to be able to turn them on and off by
resource type.
As an example:
> Value `.Values.containerRules.ContainerWaiting` has been migrated to
> `.Values.containerRules.pods.ContainerWaiting`. Please update your values
> files.
The helm chart will produce errors if you do not migrate your values files.
Proof:
```
akennedy@ndm2a prometheus-alerts % VALUES=values-akennedy.yaml make template > new
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /Users/akennedy/src/k8s-charts/charts/prometheus-alerts
Error: execution error at (prometheus-alerts/templates/containers-prometheusrule.yaml:1:4): Value `.Values.containerRules.ContainerWaiting` has been …
```
=> chore(prometheus-alerts): Group alerts by resource type

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/README.md.gotmpl, charts/prometheus-alerts/runbook.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.yaml
We ran into an issue where unbeknownst to us, our pod selector was set incorrectly and therefore all of our rules deployed via prometheus-alerts did not have any series to evaluate. This lack of series data is silently ignored. Here we are resolving this by implementing a rule which will use the various selectors to see if a basic metric exists or not. If it does not exist then we want to warn the user that none of the other rules will be evaluated.
I tried to choose metrics for each selector that were generic enough and did not rely on a specific metric that may not be gathered. Most types had an associated info or label metric which are good candidates for this use-case.
Lastly, I set the timing of this metric up for 1 hour by default. This felt okay to me as we want to be a little bit …
=> feat(prometheus-alerts): Add selector validity alarms

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/README.md.gotmpl, charts/prometheus-alerts/values.yaml
We have changed the default selectors to be more generic. This means that if you deploy multiple applications to the same namespace, and one of those applications uses this chart, then by default all applications will be monitored by these alerts. You can change this behavior by modifying the `.Values.defaults.*NameSelector` regex values.
This is a more advantageous model as (like with the individual alerts themselves) it now requires opt-out (or more specific scoping) if the default is alerting on some objects you do not want to alert on.
Historical context:
- https://github.com/Nextdoor/k8s-charts/pull/149
- https://github.com/Nextdoor/k8s-charts/pull/150
=> fix(prometheus-alerts): Make resource selectors more generic

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/_helpers.tpl
The selector for the deployment queries was looking for `kube_deployment` instead of `deployment`. However, that is not a valid label on these metrics.
Maybe this was a change upstream as it looks like our chart always used `kube_deployment`. I am surprised we have not been alerted by this more since the validity alerts have been installed.
Using these queries:
```
kube_deployment_labels{deployment!="", namespace="xyz"}
kube_deployment_status_observed_generation{deployment!="", namespace="xyz"}
kube_deployment_labels{kube_deployment!="", namespace="xyz"}
kube_deployment_status_observed_generation{kube_deployment!="", namespace="xyz"}
```
We can see that only the following values are returned:
```
kube_deployment_labels{deployment="abc",namespace="xyz",[...]} …
```
=> fix(charts/prometheus-alerts): Fix deployment selector

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.local.yaml, charts/prometheus-alerts/values.yaml
This is technically a feature - but it's so minor, I am considering it a patch. I'm just adding in an additional mechanism for setting individual labels on individual prometheus rules, which can be used to help route people to specific dashboards, or pass information to help routing the alerts in pagerduty.
Eg: Diff on `values.local.yaml`:
```diff
diranged@Matts-Macbook-Air prometheus-alerts % make template > new && diff -b -u orig new
install.go:218: [debug] Original chart version: ""
install.go:235: [debug] CHART PATH: /Users/diranged/git/nextdoor/k8s-charts/charts/prometheus-alerts
--- orig	2024-05-20 14:21:36
+++ new	2024-05-20 14:29:07
...
Update Complete. ⎈Happy Helming!⎈
@@ -116,6 +116,8 @@
for: 1m
labels:
severity: warning
+        baz: bat
+        foo: bar
- alert: …
```
=> chore(charts/prometheus-alerts): add individual label settings per alert

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml, charts/prometheus-alerts/values.yaml
There are some cases where we know the selector is fine (ie, `.*`) and yet there are not ALWAYS going to be resources that match that selector - an example would be any `Job` that is created as part of a release process... Jobs may come and go, and there may be periods of times when a `Job` does not exist, so the `kube_job_info{}` metric won't exist.
In these cases, we need an escape hatch to allow the critical alarms to exist without alerting oncall engineers just because a job is _missing_..
=> chore(prometheus-alerts): allow opting out of the validity selector alerts

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/prometheus-alerts/templates/containers-prometheusrule.yaml
1. There is no `hpa` label - I think that KSM changed that to `horizontalpodautoscaler` a while back and we never updated.
2. The alerts included all of labels from the KSM pods that the metric comes from, which was wildly confusing and makes the alarm hard to understand.
=> fix(prometheus-alerts): the hpa alerts were referencing invalid labels

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/templates/daemonset.yaml, charts/daemonset-app/templates/tests/test-connection.yaml, charts/daemonset-app/templates/tests/test-service-connection.yaml, charts/daemonset-app/values.yaml, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/templates/rollout.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/statefulset.yaml, ct.yaml
Adds template parsing on `terminationGracePeriodSeconds` in order to allow referencing or computing the termination value.
=> feat: allow using templating with terminationGracePeriodSeconds

charts/flink-job/Chart.yaml, charts/flink-job/README.md, charts/flink-job/templates/flinkjobcluster.yaml, charts/flink-job/values.yaml
This is to utilize https://github.com/spotify/flink-on-k8s-operator/pull/242
=> feat(charts/flink-job): add nodeselector to job spec

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_istio.tpl
The istio mutating webhook config can look something like this:
```
Object Selector:
Match Expressions:
Key:       sidecar.istio.io/inject
Operator:  NotIn
Values:
false
Key:       istio.io/rev
Operator:  In
Values:
stable
```
... for namespaces that are configured to be off the mesh, we'd need this change to allow single pods within that namespace to be a part of the mesh.
=> fix(nd-common): mutating webhook not working for single pod istio proxy sidecar injection

charts/local-kafka/Chart.yaml, charts/local-kafka/README.md, charts/local-kafka/templates/kafka.yaml, charts/local-kafka/values.yaml
Add support for priority class in local-kafka chart
=> chore: Add support for priority class in local-kafka chart

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/hpa.yaml, charts/rollout-app/templates/istio/virtualservice.yaml, charts/rollout-app/templates/rollout.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/deployment.yaml, charts/simple-app/templates/istio/virtualservice.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/istio/virtualservice.yaml, charts/stateful-app/values.yaml
Similar to `retries`, this PR allows users to inject custom `faults` too to their `VirtualService`: https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPFaultInjection
We also support an opinionated fault injection called `maintenanceMode`: this will create a 100% abort fault injection to abstract away the implementation from end users (it also [implicitly deactivates the HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation) while in maintenance mode)
The templates are smart enough to only render if either one of `maintenanceMode.enabled` or `faults` are set.
=> feat: enable maintenance mode (or custom HTTP fault injections)

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_authorizationpolicy.tpl, charts/nd-common/templates/_networkpolicy.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/templates/authorizationpolicy.yaml, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/authorizationpolicy.yaml, charts/simple-app/values.local.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/templates/authorizationpolicy.yaml, charts/stateful-app/values.yaml
In essence:
- If service has Istio enabled, adds `AuthorizationPolicy` that is _**analogous**_ to the existing `NetworkPolicy` that we already create (**this should be a no-op**).
- If service also enables ~`.Values.network.multiCluster.allowFromRemote`~  `.Values.network.allowAll`, we open up the NetworkPolicy to allow the AuthorizationPolicies above to take over its enforcement wholly.
To enable services in a multi-primary (Istio mesh), mult-cluster setup to be accessed from services in a different cluster (because NetworkPolicies can't enforce Ingress from **outside** the Kubernetes cluster without getting to CIDR ranges - i.e., it only knows about cluster-local namespaces. So, we allow all and instead restrict with Istio's AuthorizationPolicy)
=> feat: analogous AuthorizationPolicies to NetworkPolicies for (Istio) multi-cluster access

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_authorizationpolicy.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
You may have (for example, testing) clusters which don't have all of the Istio CRDs installed on them... in which case, you'll run into helm install failures.
=> fix(nd-common): only render AuthorizationPolicy if Istio security API is present

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_authorizationpolicy.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/values.local.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
Ref: https://github.com/Nextdoor/k8s-charts/pull/342
We have an `AuthorizationPolicy` where users can set allowedNamespaces. However, it's easy to miss the namespace of the ingress gateway that users may want their VirtualService tied to.
This parses the namespace of the istio gateways that users provide and ~creates a new list by appending it to the allowedNamespaces-provided list~ adds a separate rule for it
This is a safe assumption due to our checks of its format: https://github.com/Nextdoor/k8s-charts/blob/ca85ca6dedd25eb979e4f3f8240bd53cc424fa45/charts/simple-app/templates/istio/virtualservice.yaml#L19
Updated set `network.allowAll` and `virtualService.enabled` in values.local.yaml to `true...
Resulting relevant diff of `make template`:
```diff
--- /tmp/simple-app-orig.yaml …
```
=> chore: auto-add istio ingress gateway namespace to AuthorizationPolicy

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_authorizationpolicy.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
There may be apps that pull in and sub-chart `nd-common` , but they don't have the `virtualService: *` key set in their values.
In those cases, helm install may fail when we added https://github.com/Nextdoor/k8s-charts/pull/344.
Slightly tweaking nd-common AuthPolicy template to render cleanly in those scenarios
=> chore(nd-common): cleanly install even if virtualService field not set

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/templates/_helpers.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/_helpers.tpl, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/templates/_helpers.tpl, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/templates/_helpers.tpl
This is follow up PR to https://github.com/Nextdoor/k8s-charts/pull/350. This just updates the label names to match kubernetes standards. 
```diff
$ diff -u -b orig new
--- orig	2024-12-03 17:20:49
+++ new	2024-12-03 17:17:01
@@ -3,12 +3,12 @@
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "flink-operator" chart repository
...Successfully got an update from the "codimd" chart repository
-...Successfully got an update from the "kedacore" chart repository
...Successfully got an update from the "strimzi" chart repository
+...Successfully got an update from the "kedacore" chart repository
...Successfully got an update from the "k8s-charts" chart repository
...Successfully got an update from the "jetstack" chart repository …
```
=> chore: update version labels for all internal charts

charts/local-kafka/Chart.yaml, charts/local-kafka/README.md, charts/local-kafka/README.md.gotmpl, charts/local-kafka/ci/default-values.yaml, charts/local-kafka/ci/helm-hook-values.yaml, charts/local-kafka/ci/local-values.yaml, charts/local-kafka/templates/kafka-node-pool.yaml, charts/local-kafka/templates/kafka.yaml, charts/local-kafka/templates/user.yaml, charts/local-kafka/values.local.yaml, charts/local-kafka/values.yaml
The goal for this PR is to improve the usability of the `local-kafka` chart by reducing its startup time, introducing podAnnotations and removing old legacy settings:
We no longer see the Strimzi Operator take minutes to start up on M1 laptops, so I am removing the arbitrary startup/readiness probe delays.
Strimzi is moving to removing Zookeeper entirely in the 0.46.0 release anyways ... this change gets our local testing setup that way ahead of the change. This also reduces the number of pods that have to run locally, reducing the total startup time of a full testing environment.
If you set `.Values.podAnnotations: { ... }` now we will add these annotations to the Kafka and Entity Operator pods. This makes it easier to tell Helm to start these pods up before the rest of the tested …
=> feat(local-kafka): switch to kraft, start faster, allow annotations

charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md
I suspect that if you import multiple charts from `k8s-charts` and they reference `nd-common` it causes improper dependency resolution if the parents point to different versions of `nd-common`.
=> chore(prometheus-alerts): update nd-common dep

charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_istio.tpl
Fixes a slight backwards compatibility issue for charts that have this exact scenario (all cases must be `true`):
1. Uses  `nd-common` **_only_** as a subchart (not simple-app, et al)
2. Has `istio.enabled` set to `true`
3. Doesn't set `values.yaml` to have `istio.nativeSidecars.(...)` (which is set in simple-app et al)
In that scenario, rendering charts will give:
```
executing "nd-common.istioAnnotations" at <.Values.istio.nativeSidecars.enabled>: nil pointer evaluating interface {}.enabled
```
... this change will handle that gracefully.
Rendered simple-app with all different values ([1] no sidecars map, [2] sidecars.enabled set to true|false|"") on this branch and `main` and confirmed equal templates
=> fix(nd-common): render cleanly on sub-charting edge-case where map does not exist

.github/workflows/release.yaml, charts/simple-app/values.local.yaml
Reverts Nextdoor/k8s-charts#377
@LaikaN57 I see the release job failed with https://github.com/Nextdoor/k8s-charts/actions/runs/15605804582/job/43954897382.
Reverting to previous version for index.yaml to re-gen?
=> chore(ci): Revert Update chart releaser and bump for release

.github/workflows/release.yaml
Args changed a bit: https://github.com/helm/chart-releaser-action/tree/v1.7.0?tab=readme-ov-file#inputs
=> chore(ci): Upgrade chart-releaser to v1.7.0

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/rollout.yaml
Fixes a regression introduced in https://github.com/Nextdoor/k8s-charts/pull/384
=> fix(charts/rollout-app): use correct virtualservice name for canary istio trafficrouting

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/datadog-monitors/Chart.yaml, charts/datadog-monitors/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_common.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
Helm users occasionally override `nd-common.labels` by directly appending additional labels like:
```yaml
labels:
{{- include "nd-common.labels" . | nindent 4 }}
tags.datadoghq.com/service: nextdoor-tw
tags.datadoghq.com/version: release
```
However, when those keys (`tags.datadoghq.com/service`, etc.) already exist in the output of `nd-common.labels`, it results in a **duplicate mapping key YAML error**, such as:
```
YAMLException: duplicated mapping key (17:5)
```
This breaks `helm template` and `helm diff`, making the chart unusable when duplicate keys are involved.
---
This PR adds a new Helm helper template `nd-common.overrideCommonLabels` to allow users to safely override base labels defined in `nd-common.labels`.
---
Instead of appending labels manually, users can now do:
```yaml …
```
=> feat(charts/nd-common): add support to override common labels

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/templates/_helpers.tpl, charts/rollout-app/templates/rollout.yaml
Currently, if you have a DataDog agent running on your k8s cluster and your Argo Rollouts controller is [configured correctly](https://docs.datadoghq.com/integrations/argo-rollouts/) to allow the agent to scrape the `/metrics` endpoint for rollout metrics, you can get 90% of the granularity that you might need for the creation of a dashboard.
However, [DataDog allows](https://docs.datadoghq.com/containers/kubernetes/tag/?tab=datadogoperator) annotations to be added onto specific _ReplicaSets_ themselves for the creation of tags. These tags can have `KEY:VALUE` pairings for increased granularity into observability dashboards. This change in specific allows you to toggle between stable and canary ReplicaSets on a dashboard.
One of my applications is currently running on these changes, and …
=> feat(rollout-app): added Datadog tags for stable and canary rollout ReplicaSets

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/datadog-monitors/Chart.yaml, charts/datadog-monitors/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_datadog.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
> [!NOTE]
> This is a **chained** PR that should be merged in first before #398. This sets up that PR to properly allow potential DataDog agents to scrape any `k8s-charts.git` users Canary pods for logs.
For people using `k8s-charts.git` who use `rollout-app` and want to use DataDog for observability, the service name for the DataDog annotations is not aligned with what the _actual_ service names are. For example, within `simple-app`, the name value for `Service` kinds is: `nd-common.serviceName`. Thus, [when the DataDog Agent is trying to scrape for logs](https://docs.datadoghq.com/integrations/argo-rollouts/#log-collection), the Agent will not be able to find the correct `<LOG_CONFIG>` values. For `rollout-app`, the name is also changed to be aligned with `simple-app` in the chained PR, …
=> fix(nd-common): ensure consistent DD service names

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/datadog-monitors/Chart.yaml, charts/datadog-monitors/README.md, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_datadog.tpl, charts/prometheus-alerts/Chart.yaml, charts/prometheus-alerts/README.md, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md
Reverts the `nd-common.serviceName` change found within Nextdoor/k8s-charts#399, ensuring that versions get bumped instead of reverted.
By changing the service name within the logs here, this actually introduced a **regression**, as `nd-common.serviceName` would not be the same as `.Release.Name`. This might have caused some logs to not be scraped, thus, reverting this PR back.
=> fix(nd-common): revert #399

charts/daemonset-app/Chart.yaml, charts/daemonset-app/README.md, charts/daemonset-app/README.md.gotmpl, charts/daemonset-app/values.yaml, charts/nd-common/Chart.yaml, charts/nd-common/README.md, charts/nd-common/templates/_service.tpl, charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/README.md.gotmpl, charts/rollout-app/values.yaml, charts/simple-app/Chart.yaml, charts/simple-app/README.md, charts/simple-app/README.md.gotmpl, charts/simple-app/templates/deployment.yaml, charts/simple-app/values.yaml, charts/stateful-app/Chart.yaml, charts/stateful-app/README.md, charts/stateful-app/README.md.gotmpl, charts/stateful-app/values.yaml
As of Kubernetes v1.31, `Service` spec [supports the trafficDistribution field](https://v1-31.docs.kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution) (which is beta on v1.31.x an GA in v1.33).
For now, to ensure no side-effects, we only will set the field **_if the user explicitly sets it_**.
```
service:
trafficDistribution: PreferClose
```
This is a simple heuristic: for kube-proxy, this means prioritizing sending traffic to endpoints within the same zone as the client if an endpoint in the zone exists.
In its absence, the default routing strategy for kube-proxy is to distribute traffic to any endpoint in the cluster
Because of its straight-forward heuristic, this can possibly lead to overload, in which case setting the annotation of …
=> chore(charts/nd-common): support newer trafficDistribution field in Service

charts/rollout-app/Chart.yaml, charts/rollout-app/README.md, charts/rollout-app/templates/rollout.yaml, charts/rollout-app/templates/services.yaml
I was under the presumption that VirtualServices cannot be shared across multiple Rollout objects. However, after some testing, I was able to configure multiple rollout objects to use _one_ virtualservice object. 
I also realized that the `service.yaml` file does not make the necessary `...-canary` service that is needed when also using VirtualServices. Previously, it just made only one service, but now it creates a stable and canary service.
Setup:
Created 2 rollouts: cg-rollout-app-us-east-2a and cg-rollout-app-us-east-2b by adding the appropriate `rolloutZones` list
Created 1 VirtualService: cg-rollout-app
Both rollouts reference the same VirtualService in their traffic routing field during creation, and I was able to spin up both rollouts and their ReplicaSets without ArgoRollouts …
=> fix(rollout-app): allowed VirtualService's when AZ's are configured
